---
title: "assignment_1"
author: "Hugo TING"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
date: "2023-01-26"
---

```{r}
# Clean environment
rm(list=ls())
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Load packages
library(ggplot2)
library(RCurl)
library(tidyverse)
library(lmtest)
library(sandwich)
library(haven)
library(stargazer)
library(caret)
library(grid)
library(modelsummary)
library(scales)
library(ggcorrplot)
library(forecast)

options(scipen=999)
```

```{r }
## Loading the data from the web 
df <-  read.csv( 'https://osf.io/4ay9x/download')
```

```{r }
## Selected occupation as "Police Officer" (code = 3850)
df <-  df[df$occ2012  == '3850' ,]
```

```{r }
## predictors selection
df <-  df[, c('weight','earnwke', 'uhours', 'age', 'sex', 'marital','grade92')]
```

```{r }
## change weekly wage into hourly wage
df$HourlyWage <- (df$earnwke/df$uhours)

# age: quadratic, cubic
df <- df %>%
  mutate(agesq = age^2,
         agecu = age^3)
```

```{r}
## categorize education level
df <- df %>%
  mutate(edu_high = ifelse(grade92 > 42, 1,0),
         edu_mid = ifelse(grade92 >38 & grade92 < 43, 1,0),
         edu_low = ifelse(grade92 < 39, 1,0))
```

```{r}
## save final df
df <-  df[, c('HourlyWage', 'age', 'agesq', 'agecu', 'sex', 'marital', 'edu_high', 'edu_mid', 'edu_low')]

df <- na.omit(df)
```


# ggplot1 (lv-lv)
```{r}
ggplot(df, aes(x=age, y=HourlyWage)) +
  geom_smooth(se=FALSE) + 
  theme_bw() + 
  labs(x = "age", y = "Hourly Wage") +
  theme(plot.title = element_text(size = rel(1)))
```

# ggplot2  (lg - lv)
```{r}
# let see is log the wage will change anything
ggplot(df, aes(x=age)) +
  geom_smooth(aes(y = log(HourlyWage)), se=FALSE) + 
  theme_bw() +
  labs(x = "age", y = "ln(Hourly Wage)") +
  theme(plot.title = element_text(size = rel(1)))
```


# ggplot3  (lv - lg)
```{r}
ggplot(df, aes(x=log(age), y=HourlyWage)) +
  geom_smooth(se=FALSE) + 
  theme_bw() + 
  labs(x = "ln(age)", y = "Hourly Wage") +
  theme(plot.title = element_text(size = rel(1)))
```


# ggplot4  (lg - lg)
```{r}
ggplot(df, aes(x=log(age))) +
  geom_smooth(aes(y = log(HourlyWage)), se=FALSE) + 
  theme_bw() +
  labs(x = "ln(age)", y = "ln(Hourly Wage)") +
  theme(plot.title = element_text(size = rel(1)))
```

```{r}
# Model 1: Linear regression on age
model1 <- as.formula(HourlyWage ~ age + agesq)

# Models 2-4: Multiple linear regressions
model2 <- as.formula(HourlyWage ~ age + agesq + sex)
model3 <- as.formula(HourlyWage ~ age + agesq + sex + marital)
model4 <- as.formula(HourlyWage ~ age + agesq + sex + marital + edu_high + edu_mid + edu_low)

reg1 <- lm(model1, data=df)
reg2 <- lm(model2, data=df)
reg3 <- lm(model3, data=df)
reg4 <- lm(model4, data=df)
```

```{r}
reg1$coefficients
summary(reg1, vcov = 'sandwich')

logLik(reg1)

# Find AIC and BIC from the data
2*(reg1$rank+1) - 2*logLik(reg1)
AIC(reg1)

# BIC = k*ln(n) - 2*2*(max value of the likelihood function)
(reg1$rank+1)*log(nrow(df)) - 2*logLik(reg1)
BIC(reg1)
```

```{r}
# evaluation of the models

models <- c("reg1", "reg2","reg3", "reg4")
AIC <- c()
BIC <- c()
RMSE <- c()
RSquared <- c()
regr <- c()
k <- c()

for ( i in 1:length(models)){
  AIC[i] <- AIC(get(models[i]))
  BIC[i] <- BIC(get(models[i]))
  RMSE[i] <- RMSE(predict(get(models[i])), get(models[i])$model$HourlyWage)
  RSquared[i] <-summary(get(models[i]))$r.squared
  regr[[i]] <- coeftest(get(models[i]), vcov = sandwich)
  k[i] <- get(models[i])$rank -1
}
```

```{r}
# All models
eval <- data.frame(models, k, RSquared, RMSE, BIC)

eval <- eval %>%
  mutate(models = paste0("(",gsub("reg","",models),")")) %>%
  rename(Model = models, "R-squared" = RSquared, "Training RMSE" = RMSE, "N predictors" = k)
```

```{r}
# Cross-validation

# set number of folds
k <- 4

set.seed(13505)
cv1 <- train(model1, df, method = "lm", trControl = trainControl(method = "cv", number = k))
set.seed(13505)
cv2 <- train(model2, df, method = "lm", trControl = trainControl(method = "cv", number = k))
set.seed(13505)
cv3 <- train(model3, df, method = "lm", trControl = trainControl(method = "cv", number = k))
set.seed(13505)
cv4 <- train(model4, df, method = "lm", trControl = trainControl(method = "cv", number = k))
```

```{r}
# calculate average rmse
cv <- c("cv1", "cv2", "cv3", "cv4")
rmse_cv <- c()

for(i in 1:length(cv)){
  rmse_cv[i] <- sqrt((get(cv[i])$resample[[1]][1]^2 +
                       get(cv[i])$resample[[1]][2]^2 +
                       get(cv[i])$resample[[1]][3]^2 +
                       get(cv[i])$resample[[1]][4]^2)/4)
}


# summarize results
cv_mat <- data.frame(rbind(cv1$resample[4], "Average"),
           rbind(cv1$resample[1], rmse_cv[1]),
           rbind(cv2$resample[1], rmse_cv[2]),
           rbind(cv3$resample[1], rmse_cv[3]),
           rbind(cv4$resample[1], rmse_cv[4]))

colnames(cv_mat)<-c("Resample","Model1", "Model2", "Model3", "Model4")
cv_mat <- round(cv_mat, digits = 3)
```

```{r}

```


